insert into monthly_payments values(1,15,'TV License');
insert into monthly_payments values(1,530,'Mortgage');
insert into monthly_payments values(1,12,'Water Clean');
insert into monthly_payments values(1,92,'Council Tax');
insert into monthly_payments values(1,92,'Energy');
insert into monthly_payments values(1,33,'Work Insurance');
insert into monthly_payments values(1,,'Salary');
insert into monthly_payments values(2,15,'Car Breakdown');
insert into monthly_payments values(2,15,'Car Tax');
insert into monthly_payments values(4,17,'Home Insurance');
insert into monthly_payments values(5,12,'Mobile Phone');
insert into monthly_payments values(6,18,'Broadband');
insert into monthly_payments values(10,10,'Water Dirty');
insert into monthly_payments values(10,12,'Alzheimer');
insert into monthly_payments values(17,4,'Webcam');
insert into monthly_payments values(18,24,'Car insurance');
insert into monthly_payments values(19,12,'Mind');
insert into monthly_payments values(21,9,'Life Insurance');
insert into monthly_payments values(24,40,'Bank fees');
